language: node_js
node_js:
- '5.1'
- '4.2'
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
install:
- npm install
- npm install react
after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls' | ./node_modules/coveralls/bin/coveralls.js